Repository fastly/terraform-provider-fastly, pull requests merged in 2018-09, with the labels that each got.

#92 Add explanation for importing service
  website/docs/r/service_v1.html.markdown
Labels: size/XS

#90 Bigquery template
  fastly/resource_fastly_service_v1.go
  vendor/github.com/sethvargo/go-fastly/fastly/bigquery.go
  vendor/github.com/sethvargo/go-fastly/fastly/dictionary.go
  vendor/github.com/sethvargo/go-fastly/fastly/dictionary_item.go
  vendor/vendor.json
  website/docs/r/service_v1.html.markdown
Labels: size/M

#93 Add support for VCL Snippets
  fastly/resource_fastly_service_v1.go
  fastly/resource_fastly_service_v1_cache_setting_test.go
  fastly/resource_fastly_service_v1_snippet_test.go
  vendor/github.com/sethvargo/go-fastly/fastly/errors.go
  vendor/github.com/sethvargo/go-fastly/fastly/vcl_snippets.go
  vendor/vendor.json
  website/docs/r/service_v1.html.markdown
Labels: size/XL

#43 Added support for custom Directors
  fastly/resource_fastly_service_v1.go
  fastly/resource_fastly_service_v1_director_test.go
  fastly/validators.go
  fastly/validators_test.go
  vendor/github.com/sethvargo/go-fastly/fastly/acl.go
  vendor/github.com/sethvargo/go-fastly/fastly/acl_entry.go
  vendor/github.com/sethvargo/go-fastly/fastly/backend.go
  vendor/github.com/sethvargo/go-fastly/fastly/condition.go
  vendor/github.com/sethvargo/go-fastly/fastly/dictionary.go
  vendor/github.com/sethvargo/go-fastly/fastly/director.go
  vendor/github.com/sethvargo/go-fastly/fastly/domain.go
  vendor/github.com/sethvargo/go-fastly/fastly/health_check.go
  vendor/github.com/sethvargo/go-fastly/fastly/vcl_snippets.go
  vendor/vendor.json
  website/docs/r/service_v1.html.markdown
Labels: size/XL

#97 Add argument reference for bigquerylogging
  website/docs/r/service_v1.html.markdown
Labels: size/XS
