Repository fastly/terraform-provider-fastly, pull requests merged in 2019-06, with the labels that each got.

#160 Fixing acceptance tests
  fastly/provider_test.go
  fastly/resource_fastly_service_v1_bigquerylogging_test.go
  fastly/resource_fastly_service_v1_gcslogging_test.go
  fastly/resource_fastly_service_v1_s3logging_test.go
  fastly/resource_fastly_service_v1_sumologic_test.go
Labels: size/L

#162 Introduces and refactors flatten function unit tests.
  fastly/resource_fastly_service_v1_cache_setting_test.go
  fastly/resource_fastly_service_v1_conditionals_test.go
  fastly/resource_fastly_service_v1_director_test.go
  fastly/resource_fastly_service_v1_gzip_test.go
  fastly/resource_fastly_service_v1_headers_test.go
  fastly/resource_fastly_service_v1_healthcheck_test.go
  fastly/resource_fastly_service_v1_logentries_test.go
  fastly/resource_fastly_service_v1_papertrail_test.go
  fastly/resource_fastly_service_v1_request_setting_test.go
  fastly/resource_fastly_service_v1_response_object_test.go
  fastly/resource_fastly_service_v1_snippet_test.go
  fastly/resource_fastly_service_v1_syslog_test.go
  fastly/resource_fastly_service_v1_vcl_test.go
Labels: size/XL

#149 Add validation for condition type attribute
  fastly/resource_fastly_service_v1.go
  fastly/validators.go
  fastly/validators_test.go
  vendor/github.com/hashicorp/terraform/helper/structure/expand_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/flatten_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/normalize_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/suppress_json_diff.go
  vendor/github.com/hashicorp/terraform/helper/validation/validation.go
  vendor/modules.txt
Labels: dependencies, enhancement, size/XL

#159 Adding terraform provider version to user-agent header
  CHANGELOG.md
  GNUmakefile
  fastly/config.go
  fastly/config_test.go
  version/version.go
Labels: size/S

#164 Refactor validators
  fastly/resource_fastly_service_v1.go
  fastly/validators.go
  fastly/validators_test.go
Labels: size/XL

#165 Add support for override host field
  fastly/resource_fastly_service_v1.go
  fastly/resource_fastly_service_v1_bigquerylogging_test.go
  fastly/resource_fastly_service_v1_director_test.go
  fastly/resource_fastly_service_v1_snippet_test.go
  fastly/resource_fastly_service_v1_test.go
  go.mod
  go.sum
  vendor/github.com/fastly/go-fastly/fastly/acl.go
  vendor/github.com/fastly/go-fastly/fastly/acl_entry.go
  vendor/github.com/fastly/go-fastly/fastly/backend.go
  vendor/github.com/fastly/go-fastly/fastly/bigquery.go
  vendor/github.com/fastly/go-fastly/fastly/cache_setting.go
  vendor/github.com/fastly/go-fastly/fastly/client.go
  vendor/github.com/fastly/go-fastly/fastly/condition.go
  vendor/github.com/fastly/go-fastly/fastly/dictionary.go
  vendor/github.com/fastly/go-fastly/fastly/dictionary_item.go
  vendor/github.com/fastly/go-fastly/fastly/director.go
  vendor/github.com/fastly/go-fastly/fastly/domain.go
  vendor/github.com/fastly/go-fastly/fastly/errors.go
  vendor/github.com/fastly/go-fastly/fastly/event_logs.go
  vendor/github.com/fastly/go-fastly/fastly/ftp.go
  vendor/github.com/fastly/go-fastly/fastly/gcs.go
  vendor/github.com/fastly/go-fastly/fastly/gzip.go
  vendor/github.com/fastly/go-fastly/fastly/header.go
  vendor/github.com/fastly/go-fastly/fastly/health_check.go
  vendor/github.com/fastly/go-fastly/fastly/papertrail.go
  vendor/github.com/fastly/go-fastly/fastly/request_setting.go
  vendor/github.com/fastly/go-fastly/fastly/response_object.go
  vendor/github.com/fastly/go-fastly/fastly/service.go
  vendor/github.com/fastly/go-fastly/fastly/vcl.go
  vendor/github.com/fastly/go-fastly/fastly/vcl_snippets.go
  vendor/github.com/fastly/go-fastly/fastly/version.go
  vendor/modules.txt
  website/docs/r/service_v1.html.markdown
Labels: dependencies, documentation, size/XL

#145 Add support for splunk logging
  fastly/resource_fastly_service_v1.go
  fastly/resource_fastly_service_v1_splunk_test.go
  website/docs/r/service_v1.html.markdown
Labels: dependencies, documentation, enhancement, size/XL

#138 Add support for service comment field
  fastly/resource_fastly_service_v1.go
  fastly/resource_fastly_service_v1_test.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, enhancement, size/M

#169 Add support for version comment field
  fastly/resource_fastly_service_v1.go
  fastly/resource_fastly_service_v1_test.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/S

#168 Add support for blob storage logging
  fastly/resource_fastly_service_v1.go
  fastly/resource_fastly_service_v1_blobstoragelogging_test.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#170 Adjust tests due to go-fastly v1.0.0 update
  fastly/resource_fastly_service_v1_cache_setting_test.go
  fastly/resource_fastly_service_v1_conditionals_test.go
  fastly/resource_fastly_service_v1_gzip_test.go
  fastly/resource_fastly_service_v1_headers_test.go
  fastly/resource_fastly_service_v1_healthcheck_test.go
  fastly/resource_fastly_service_v1_papertrail_test.go
  fastly/resource_fastly_service_v1_request_setting_test.go
  fastly/resource_fastly_service_v1_response_object_test.go
Labels: size/XS

#172 Accept PREFETCH condition type value
  fastly/validators.go
  fastly/validators_test.go
Labels: enhancement, size/XS

#174 Revert "Accept PREFETCH condition type value"
  fastly/validators.go
  fastly/validators_test.go
Labels: size/XS
