Repository fastly/terraform-provider-fastly, pull requests merged in 2019-01, with the labels that each got.

#116 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
  README.md
  fastly/data_source_ip_ranges.go
  fastly/data_source_ip_ranges_test.go
  fastly/provider.go
  fastly/resource_fastly_service_v1_bigquerylogging_test.go
  fastly/resource_fastly_service_v1_cache_setting_test.go
  fastly/resource_fastly_service_v1_conditionals_test.go
  fastly/resource_fastly_service_v1_director_test.go
  fastly/resource_fastly_service_v1_gcslogging_test.go
  fastly/resource_fastly_service_v1_gzip_test.go
  fastly/resource_fastly_service_v1_headers_test.go
  fastly/resource_fastly_service_v1_healthcheck_test.go
  fastly/resource_fastly_service_v1_papertrail_test.go
  fastly/resource_fastly_service_v1_request_setting_test.go
  fastly/resource_fastly_service_v1_response_object_test.go
  fastly/resource_fastly_service_v1_snippet_test.go
  fastly/resource_fastly_service_v1_sumologic_test.go
  fastly/resource_fastly_service_v1_test.go
  fastly/resource_fastly_service_v1_vcl_test.go
Labels: size/M

#120 provider: Enable request/response logging
  fastly/config.go
Labels: enhancement, size/XS

#45 add `activate` argument
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/S

#118 update list of exported attributes
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XS

#121 Fix VCL snippet acceptance test
  fastly/resource_fastly_service_v1_snippet_test.go
Labels: size/M
