Repository fastly/terraform-provider-fastly, pull requests merged in 2019-08, with the labels that each got.

#186 Fix documentation sidebar navigation links and markdown rendering
  website/docs/r/service_acl_entries_v1.html.markdown
  website/docs/r/service_dictionary_items_v1.html.markdown
  website/docs/r/service_dynamic_snippet_content_v1.html.markdown
  website/fastly.erb
Labels: documentation, size/L

#185 Refactor CHANGELOG for consistency
  CHANGELOG.md
Labels: size/M

#187 Fix checksums in go.sum
  .go-version
  go.sum
Labels: size/S
