Repository fastly/terraform-provider-fastly, pull requests merged in 2020-07, with the labels that each got.

#282 Update changelog for release (v0.18.0)
  CHANGELOG.md
Labels: size/XS

#281 Add package and basic Wasm service
  fastly/base_fastly_service_v1.go
  fastly/block_fastly_service_v1_package.go
  fastly/block_fastly_service_v1_package_test.go
  fastly/provider.go
  fastly/resource_fastly_service_compute_v1.go
  fastly/resource_fastly_service_compute_v1_test.go
  fastly/test_fixtures/package/invalid.tar.gz
  fastly/test_fixtures/package/valid.tar.gz
  fastly/test_fixtures/package/valid2.tar.gz
  go.mod
  go.sum
  vendor/github.com/fastly/go-fastly/fastly/client.go
  vendor/github.com/fastly/go-fastly/fastly/dictionary_item.go
  vendor/github.com/fastly/go-fastly/fastly/package.go
  vendor/github.com/fastly/go-fastly/fastly/realtime_stats.go
  vendor/github.com/fastly/go-fastly/fastly/stats.go
  vendor/github.com/fastly/go-fastly/fastly/tls.go
  vendor/modules.txt
Labels: dependencies, size/XL

#286 Import for Compute services
  fastly/base_fastly_service_v1.go
  fastly/resource_fastly_service_compute_test.go
  fastly/resource_fastly_service_v1_test.go
Labels: size/L

#290 Fix error check in s3_logging which was causing runtime panic
  fastly/block_fastly_service_v1_s3logging.go
Labels: size/XS

#292 Fix message_type attribute in ftp_loggging tests
  fastly/block_fastly_service_v1_logging_ftp_test.go
Labels: size/XS

#293 Update changelog for v0.19.0 release.
  CHANGELOG.md
Labels: size/XS

#294 Regenerate website documentation for compute service
  website/docs/r/service_compute.html.markdown
Labels: documentation, size/XS

#295 v0.19.1 hangelog
  CHANGELOG.md
Labels: documentation, size/XS

#296 Fix resource references in compute documentation
  website/docs/r/service_compute.html.markdown
  website/docs/r/service_v1.html.markdown
  website_src/docs/r/components/footer.markdown.tmpl
  website_src/docs/r/service_compute.html.markdown.tmpl
Labels: documentation, size/M

#297 Update CHANGELOG.md for v0.19.2
  CHANGELOG.md
Labels: size/XS
