Repository fastly/terraform-provider-fastly, pull requests merged in 2020-01, with the labels that each got.

#194 Fix document
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XS

#203 Add tls client auth support for syslog
  fastly/provider_test.go
  fastly/resource_fastly_service_v1.go
  fastly/resource_fastly_service_v1_syslog_test.go
  go.mod
  go.sum
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/fastly/go-fastly/fastly/client.go
  vendor/github.com/fastly/go-fastly/fastly/decode_hooks.go
  vendor/github.com/fastly/go-fastly/fastly/dictionary_info.go
  vendor/github.com/fastly/go-fastly/fastly/errors.go
  vendor/github.com/fastly/go-fastly/fastly/fastly.go
  vendor/github.com/fastly/go-fastly/fastly/service.go
  vendor/github.com/fastly/go-fastly/fastly/syslog.go
  vendor/github.com/fastly/go-fastly/fastly/token.go
  vendor/github.com/fastly/go-fastly/fastly/vcl_snippets.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
  website/docs/r/service_v1.html.markdown
Labels: dependencies, documentation, size/XXL

#205 Fix setting default_ttl to 0 on create
  fastly/resource_fastly_service_v1.go
  fastly/resource_fastly_service_v1_test.go
Labels: size/M
