Repository fastly/terraform-provider-fastly, pull requests merged in 2020-06, with the labels that each got.

#240 Fastly IP Ranges (ipv6_cidr_blocks)
  fastly/data_source_ip_ranges.go
  fastly/data_source_ip_ranges_test.go
  go.mod
  go.sum
  vendor/github.com/fastly/go-fastly/fastly/client.go
  vendor/github.com/fastly/go-fastly/fastly/ip.go
  vendor/modules.txt
  website/docs/d/ip_ranges.html.markdown
Labels: dependencies, documentation, size/M

#245 Update changelog for release (v0.16.0)
  CHANGELOG.md
Labels: size/XS

#246 Adding missing server_side_encryption and server_side_encryption_kms_…
  fastly/resource_fastly_service_v1.go
Labels: size/S

#247 Update changelog for release (v0.16.1)
  CHANGELOG.md
Labels: size/XS

#248 mod: upgrade fastly/go-fastly v1.14.0 -> v1.15.0
  go.mod
  go.sum
  vendor/github.com/fastly/go-fastly/fastly/client.go
  vendor/github.com/fastly/go-fastly/fastly/cloudfiles.go
  vendor/github.com/fastly/go-fastly/fastly/gcs.go
  vendor/github.com/fastly/go-fastly/fastly/kafka.go
  vendor/github.com/fastly/go-fastly/fastly/s3.go
  vendor/github.com/fastly/go-fastly/fastly/scalyr.go
  vendor/github.com/fastly/go-fastly/fastly/sftp.go
  vendor/modules.txt
Labels: dependencies, size/XS

#250 Update regarding customer VCL.
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XS

#235 Add support for FTP logging
  fastly/block_fastly_service_v1_logging_ftp.go
  fastly/block_fastly_service_v1_logging_ftp_test.go
  fastly/fastly_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#253 Acl block to file
  fastly/block_fastly_service_v1_acl.go
  fastly/block_fastly_service_v1_acl_test.go
  fastly/resource_fastly_service_v1.go
Labels: size/L

#257 Update docs.fastly.com links
  fastly/resource_fastly_service_v1.go
  fastly/resource_fastly_service_v1_director_test.go
  website/docs/r/service_acl_entries_v1.html.markdown
  website/docs/r/service_dictionary_items_v1.html.markdown
  website/docs/r/service_dynamic_snippet_content_v1.html.markdown
  website/docs/r/service_v1.html.markdown
Labels: dependencies, documentation, size/S

#236 Add support for SFTP logging
  fastly/block_fastly_service_v1_logging_sftp.go
  fastly/block_fastly_service_v1_logging_sftp_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#262 Migration of all blocks to their own files
  fastly/block_fastly_service_v1_backend.go
  fastly/block_fastly_service_v1_bigquerylogging.go
  fastly/block_fastly_service_v1_blobstoragelogging.go
  fastly/block_fastly_service_v1_blobstoragelogging_test.go
  fastly/block_fastly_service_v1_cachesetting.go
  fastly/block_fastly_service_v1_cachesetting_test.go
  fastly/block_fastly_service_v1_condition.go
  fastly/block_fastly_service_v1_condition_test.go
  fastly/block_fastly_service_v1_dictionary.go
  fastly/block_fastly_service_v1_dictionary_test.go
  fastly/block_fastly_service_v1_director.go
  fastly/block_fastly_service_v1_director_test.go
  fastly/block_fastly_service_v1_domain.go
  fastly/block_fastly_service_v1_dynamicsnippet.go
  fastly/block_fastly_service_v1_dynamicsnippet_test.go
  fastly/block_fastly_service_v1_gcslogging.go
  fastly/block_fastly_service_v1_gcslogging_test.go
  fastly/block_fastly_service_v1_gzip.go
  fastly/block_fastly_service_v1_gzip_test.go
  fastly/block_fastly_service_v1_header.go
  fastly/block_fastly_service_v1_header_test.go
  fastly/block_fastly_service_v1_healthcheck.go
  fastly/block_fastly_service_v1_healthcheck_test.go
  fastly/block_fastly_service_v1_logentries.go
  fastly/block_fastly_service_v1_logentries_test.go
  fastly/block_fastly_service_v1_papertrail.go
  fastly/block_fastly_service_v1_papertrail_test.go
  fastly/block_fastly_service_v1_requestsetting.go
  fastly/block_fastly_service_v1_requestsetting_test.go
  fastly/block_fastly_service_v1_responseobject.go
  fastly/block_fastly_service_v1_responseobject_test.go
  fastly/block_fastly_service_v1_s3logging.go
  fastly/block_fastly_service_v1_s3logging_test.go
  fastly/block_fastly_service_v1_snippet.go
  fastly/block_fastly_service_v1_snippet_test.go
  fastly/block_fastly_service_v1_splunk.go
  fastly/block_fastly_service_v1_splunk_test.go
  fastly/block_fastly_service_v1_sumologic.go
  fastly/block_fastly_service_v1_sumologic_test.go
  fastly/block_fastly_service_v1_syslog.go
  fastly/block_fastly_service_v1_syslog_test.go
  fastly/block_fastly_service_v1_vcl.go
  fastly/block_fastly_service_v1_vcl_test.go
  fastly/resource_fastly_service_v1.go
Labels: size/XXL

#242 Add support for Datadog logging
  fastly/block_fastly_service_v1_logging_datadog.go
  fastly/block_fastly_service_v1_logging_datadog_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#241 Add support for Loggly logging
  fastly/block_fastly_service_v1_logging_loggly.go
  fastly/block_fastly_service_v1_logging_loggly_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#259 Elasticsearch, FTP and SFTP Omitted Refresh
  fastly/block_fastly_service_v1_logging_elasticsearch_test.go
  fastly/resource_fastly_service_v1.go
Labels: size/S

#249 S3 Logging PublicKey field support
  fastly/block_fastly_service_v1_s3logging.go
  fastly/block_fastly_service_v1_s3logging_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: dependencies, documentation, size/L

#243 Add support for New Relic logging
  fastly/block_fastly_service_v1_logging_newrelic.go
  fastly/block_fastly_service_v1_logging_newrelic_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#252 Adds Scalyr Logging Endpoint Support
  fastly/block_fastly_service_v1_logging_scalyr.go
  fastly/block_fastly_service_v1_logging_scalyr_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#258 Adds Google Cloud Pub/Sub Logging Endpoint Support
  fastly/block_fastly_service_v1_logging_googlepubsub.go
  fastly/block_fastly_service_v1_logging_googlepubsub_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#263 helpers: add test helper for escaping '%'
  fastly/block_fastly_service_v1_logging_datadog_test.go
  fastly/block_fastly_service_v1_logging_newrelic_test.go
  fastly/fastly_test.go
Labels: size/M

#264 Handle TLS Whitespace
  fastly/block_fastly_service_v1_httpslogging.go
  fastly/block_fastly_service_v1_logging_elasticsearch.go
  fastly/block_fastly_service_v1_logging_elasticsearch_test.go
  fastly/block_fastly_service_v1_splunk.go
  fastly/fastly_test.go
  fastly/statefuncs.go
Labels: size/M

#254 Adds Kafka Logging Endpoint Support
  fastly/block_fastly_service_v1_logging_kafka.go
  fastly/block_fastly_service_v1_logging_kafka_test.go
  fastly/fastly_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: dependencies, documentation, size/XL

#265 Update Elasticsearch docs noting default values
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XS

#268 tests: use armored pgp key
  fastly/block_fastly_service_v1_bigquerylogging.go
  fastly/block_fastly_service_v1_logging_sftp.go
  fastly/block_fastly_service_v1_logging_sftp_test.go
  fastly/fastly_test.go
Labels: size/M

#266 Update changelog for release (v0.17.0)
  CHANGELOG.md
Labels: size/XS

#269 OC Migrate Blocks to using AttributeHandlers
  fastly/base_fastly_service_v1.go
  fastly/block_fastly_service_v1_acl.go
  fastly/block_fastly_service_v1_backend.go
  fastly/block_fastly_service_v1_bigquerylogging.go
  fastly/block_fastly_service_v1_bigquerylogging_test.go
  fastly/block_fastly_service_v1_blobstoragelogging.go
  fastly/block_fastly_service_v1_cachesetting.go
  fastly/block_fastly_service_v1_condition.go
  fastly/block_fastly_service_v1_dictionary.go
  fastly/block_fastly_service_v1_director.go
  fastly/block_fastly_service_v1_domain.go
  fastly/block_fastly_service_v1_dynamicsnippet.go
  fastly/block_fastly_service_v1_gcslogging.go
  fastly/block_fastly_service_v1_gzip.go
  fastly/block_fastly_service_v1_header.go
  fastly/block_fastly_service_v1_healthcheck.go
  fastly/block_fastly_service_v1_httpslogging.go
  fastly/block_fastly_service_v1_logentries.go
  fastly/block_fastly_service_v1_logging_datadog.go
  fastly/block_fastly_service_v1_logging_elasticsearch.go
  fastly/block_fastly_service_v1_logging_elasticsearch_test.go
  fastly/block_fastly_service_v1_logging_ftp.go
  fastly/block_fastly_service_v1_logging_ftp_test.go
  fastly/block_fastly_service_v1_logging_googlepubsub.go
  fastly/block_fastly_service_v1_logging_googlepubsub_test.go
  fastly/block_fastly_service_v1_logging_kafka.go
  fastly/block_fastly_service_v1_logging_kafka_test.go
  fastly/block_fastly_service_v1_logging_loggly.go
  fastly/block_fastly_service_v1_logging_newrelic.go
  fastly/block_fastly_service_v1_logging_scalyr.go
  fastly/block_fastly_service_v1_logging_sftp.go
  fastly/block_fastly_service_v1_logging_sftp_test.go
  fastly/block_fastly_service_v1_papertrail.go
  fastly/block_fastly_service_v1_requestsetting.go
  fastly/block_fastly_service_v1_responseobject.go
  fastly/block_fastly_service_v1_s3logging.go
  fastly/block_fastly_service_v1_s3logging_test.go
  fastly/block_fastly_service_v1_settings.go
  fastly/block_fastly_service_v1_snippet.go
  fastly/block_fastly_service_v1_splunk.go
  fastly/block_fastly_service_v1_sumologic.go
  fastly/block_fastly_service_v1_syslog.go
  fastly/block_fastly_service_v1_vcl.go
  fastly/fastly_test.go
  fastly/resource_fastly_service_v1.go
  fastly/test_fixtures/fastly_test_cacert
  fastly/test_fixtures/fastly_test_certificate
  fastly/test_fixtures/fastly_test_privatekey
  fastly/test_fixtures/fastly_test_publickey
Labels: size/XXL

#270 Update changelog for release (v0.17.1)
  CHANGELOG.md
Labels: size/XS

#271 Adds Heroku logging support
  fastly/block_fastly_service_v1_logging_heroku.go
  fastly/block_fastly_service_v1_logging_heroku_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#272 Adds Honeycomb logging support
  fastly/block_fastly_service_v1_logging_honeycomb.go
  fastly/block_fastly_service_v1_logging_honeycomb_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#273 Adds Log Shuttle logging support
  fastly/block_fastly_service_v1_logging_logshuttle.go
  fastly/block_fastly_service_v1_logging_logshuttle_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#274 Adds OpenStack logging support
  fastly/block_fastly_service_v1_logging_openstack.go
  fastly/block_fastly_service_v1_openstack_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#276 Adds DigitalOcean Spaces logging endpoint support
  fastly/block_fastly_service_v1_logging_digitalocean.go
  fastly/block_fastly_service_v1_logging_digitalocean_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#277 Ensure PublicKey field is using trimSpaceStateFunc
  fastly/block_fastly_service_v1_blobstoragelogging.go
  fastly/block_fastly_service_v1_logging_ftp.go
  fastly/block_fastly_service_v1_s3logging.go
Labels: size/S

#278 Adds message_type validation func to SFTP and GCS
  fastly/block_fastly_service_v1_gcslogging.go
  fastly/block_fastly_service_v1_logging_sftp.go
Labels: size/XS

#275 Adds Rackspace Cloud Files logging support
  fastly/block_fastly_service_v1_logging_cloudfiles.go
  fastly/block_fastly_service_v1_logging_cloudfiles_test.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#280 Update Azure Blob Storage Tests to Use Helper
  fastly/block_fastly_service_v1_blobstoragelogging_test.go
Labels: size/XS

#279 GZIP -> Gzip
  fastly/block_fastly_service_v1_gzip.go
  fastly/block_fastly_service_v1_logging_digitalocean.go
  fastly/block_fastly_service_v1_logging_openstack.go
  fastly/block_fastly_service_v1_logging_sftp.go
  fastly/resource_fastly_service_v1.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/S
