Repository fastly/terraform-provider-fastly, pull requests merged in 2020-04, with the labels that each got.

#217 Fix support for `hash` type snippets.
  fastly/resource_fastly_service_v1.go
Labels: size/XS

#215 Bump CI to go 1.14
  .travis.yml
  README.md
  go.mod
  vendor/github.com/fastly/go-fastly/fastly/user.go
  vendor/modules.txt
Labels: dependencies, size/L

#214 Add ability to terraform fastly users
  fastly/provider.go
  fastly/resource_fastly_user_v1.go
  fastly/resource_fastly_user_v1_test.go
  fastly/validators.go
  fastly/validators_test.go
  website/docs/r/user_v1.html.markdown
  website/fastly.erb
Labels: documentation, size/XL

#219 Update Changelog for release (0.14.0)
  CHANGELOG.md
Labels: size/XS

#220 Update go-fastly to v1.10.0
  go.mod
  go.sum
  vendor/github.com/fastly/go-fastly/fastly/client.go
  vendor/github.com/fastly/go-fastly/fastly/errors.go
  vendor/github.com/fastly/go-fastly/fastly/https.go
  vendor/github.com/fastly/go-fastly/fastly/platform_tls.go
  vendor/github.com/fastly/go-fastly/fastly/splunk.go
  vendor/github.com/fastly/go-fastly/fastly/tls.go
  vendor/modules.txt
Labels: dependencies, size/XL

#221 Add `tls_hostname` and `tls_ca_cert` fields to splunk logging
  fastly/resource_fastly_service_v1.go
  fastly/resource_fastly_service_v1_splunk_test.go
  website/docs/r/service_v1.html.markdown
Labels: dependencies, documentation, size/L

#222 Add support for HTTPS logging
  fastly/block_fastly_service_v1_httpslogging.go
  fastly/block_fastly_service_v1_httpslogging_test.go
  fastly/resource_fastly_service_v1.go
  fastly/validators.go
  fastly/validators_test.go
  website/docs/r/service_v1.html.markdown
Labels: documentation, size/XL

#223 Update changelog for release (0.15.0)
  CHANGELOG.md
Labels: size/XS
