Repository fastly/terraform-provider-fastly, pull requests merged in 2021-04, with the labels that each got.

#387 Fix misleading diff bug for backends
  fastly/block_fastly_service_v1_backend.go
Labels: bug

#392 Include dns_records in TLS configuration when performing lookup by ID
  fastly/data_source_fastly_tls_configuration.go
Labels: bug

#390 When updating service, clone the cloned_version instead of active_version
  docs/resources/service_compute.md
  docs/resources/service_v1.md
  fastly/base_fastly_service_v1.go
  fastly/block_fastly_service_v1_acl_test.go
  fastly/resource_fastly_service_v1_test.go
Labels: bug

#396 Catch case where state from older version could be unexpected
  fastly/base_fastly_service_v1.go
Labels: bug

#398 Add support for file_max_bytes configuration for azure logging endpoint
  docs/resources/service_compute.md
  docs/resources/service_v1.md
  fastly/block_fastly_service_v1_blobstoragelogging.go
  fastly/block_fastly_service_v1_blobstoragelogging_test.go
Labels: enhancement

#403 Support usage of IAM role in S3 and Kinesis logging endpoints
  docs/resources/service_compute.md
  docs/resources/service_v1.md
  fastly/block_fastly_service_v1_logging_kinesis.go
  fastly/block_fastly_service_v1_logging_kinesis_test.go
  fastly/block_fastly_service_v1_s3logging.go
  fastly/block_fastly_service_v1_s3logging_test.go
  go.mod
  go.sum
  vendor/github.com/fastly/go-fastly/v3/fastly/client.go
  vendor/github.com/fastly/go-fastly/v3/fastly/kinesis.go
  vendor/github.com/fastly/go-fastly/v3/fastly/s3.go
  vendor/modules.txt
Labels: enhancement

#402 Add support for compression_codec to logging file sink endpoints
  docs/resources/service_compute.md
  docs/resources/service_v1.md
  fastly/block_fastly_service_v1_blobstoragelogging.go
  fastly/block_fastly_service_v1_blobstoragelogging_test.go
  fastly/block_fastly_service_v1_gcslogging.go
  fastly/block_fastly_service_v1_gcslogging_test.go
  fastly/block_fastly_service_v1_logging_cloudfiles.go
  fastly/block_fastly_service_v1_logging_cloudfiles_test.go
  fastly/block_fastly_service_v1_logging_digitalocean.go
  fastly/block_fastly_service_v1_logging_digitalocean_test.go
  fastly/block_fastly_service_v1_logging_ftp.go
  fastly/block_fastly_service_v1_logging_ftp_test.go
  fastly/block_fastly_service_v1_logging_openstack.go
  fastly/block_fastly_service_v1_logging_openstack_test.go
  fastly/block_fastly_service_v1_logging_sftp.go
  fastly/block_fastly_service_v1_logging_sftp_test.go
  fastly/block_fastly_service_v1_s3logging.go
  fastly/block_fastly_service_v1_s3logging_test.go
  fastly/validators.go
Labels: enhancement

#405 Update debug mode instructions for TF 0.12.x
  README.md
Labels: documentation
