Repository fastly/terraform-provider-fastly, pull requests merged in 2021-03, with the labels that each got.

#376 Better sensitive value handling in Google pub/sub logging provider
  docs/resources/service_compute.md
  docs/resources/service_v1.md
  fastly/block_fastly_service_v1_logging_googlepubsub.go
  fastly/block_fastly_service_v1_logging_googlepubsub_test.go
Labels: enhancement

#377 Fix panic caused by incorrect type assert.
  fastly/block_fastly_service_v1_gzip.go
  fastly/block_fastly_service_v1_gzip_test.go
Labels: bug

#384 Terraform 0.11 and earlier required all non-constant expressions to be provided via interpolation syntax
  docs/data-sources/ip_ranges.md
  templates/data-sources/ip_ranges.md.tmpl
Labels: documentation

#386 Add debug mode
  README.md
  main.go
Labels: enhancement

#389 Ensure passwords are marked as sensitive.
  docs/resources/service_compute.md
  docs/resources/service_v1.md
  fastly/block_fastly_service_v1_logging_kafka.go
Labels: enhancement
