Repository fastly/terraform-provider-fastly, pull requests merged in 2021-07, with the labels that each got.

#439 replace StateFunc with ValidateDiagFunc
  fastly/block_fastly_service_v1_bigquerylogging.go
  fastly/block_fastly_service_v1_bigquerylogging_test.go
  fastly/block_fastly_service_v1_blobstoragelogging.go
  fastly/block_fastly_service_v1_httpslogging.go
  fastly/block_fastly_service_v1_logging_cloudfiles.go
  fastly/block_fastly_service_v1_logging_digitalocean.go
  fastly/block_fastly_service_v1_logging_elasticsearch.go
  fastly/block_fastly_service_v1_logging_ftp.go
  fastly/block_fastly_service_v1_logging_kafka.go
  fastly/block_fastly_service_v1_logging_openstack.go
  fastly/block_fastly_service_v1_logging_sftp.go
  fastly/block_fastly_service_v1_s3logging.go
  fastly/block_fastly_service_v1_splunk.go
  fastly/statefuncs.go
  fastly/tls_test.go
  fastly/validators.go
Labels: enhancement

#388 Output variable refresh bug
  fastly/base_fastly_service_v1.go
Labels: bug

#440 Fix parsing of log-levels by removing date/time prefix
  main.go
Labels: bug

#444 Introduce "no_auth" provider option
  docs/data-sources/ip_ranges.md
  docs/index.md
  fastly/config.go
  fastly/data_source_ip_ranges.go
  fastly/data_source_ip_ranges_test.go
  fastly/provider.go
  templates/data-sources/ip_ranges.md.tmpl
  templates/index.md
Labels: enhancement

#445 add limitations for write_only dictionaries
  docs/resources/service_dictionary_items_v1.md
  templates/resources/service_dictionary_items_v1.md.tmpl
Labels: documentation

#446 set main field on CreateVCL to reduce redundant subsequent call
  fastly/block_fastly_service_v1_vcl.go
Labels: enhancement

#435 [bug] fix fastly_tls_subscription resource to properly handle challenges for multi-SAN
  docs/resources/tls_subscription.md
  fastly/resource_fastly_tls_subscription.go
  templates/resources/tls_subscription.md.tmpl
Labels: bug, v1.0.0

#448 Simplify Service import logic, and allow selecting a version while importing
  docs/resources/service_compute.md
  docs/resources/service_v1.md
  fastly/base_fastly_service_v1.go
  fastly/resource_fastly_service_v1_test.go
  templates/resources/components/footer.md.tmpl
Labels: enhancement
