Repository fastly/terraform-provider-fastly, pull requests merged in 2021-09, with the labels that each got.

#466 Correctly update `version_comment`
  fastly/base_fastly_service_v1.go
  fastly/resource_fastly_service_v1_test.go
Labels: bug

#463 Refactor service attribute handlers into CRUD-style functions
  fastly/base_fastly_service_v1.go
  fastly/block_fastly_service_v1_acl.go
  fastly/block_fastly_service_v1_backend.go
  fastly/block_fastly_service_v1_bigquerylogging.go
  fastly/block_fastly_service_v1_blobstoragelogging.go
  fastly/block_fastly_service_v1_cachesetting.go
  fastly/block_fastly_service_v1_condition.go
  fastly/block_fastly_service_v1_dictionary.go
  fastly/block_fastly_service_v1_director.go
  fastly/block_fastly_service_v1_domain.go
  fastly/block_fastly_service_v1_dynamicsnippet.go
  fastly/block_fastly_service_v1_gcslogging.go
  fastly/block_fastly_service_v1_gzip.go
  fastly/block_fastly_service_v1_header.go
  fastly/block_fastly_service_v1_healthcheck.go
  fastly/block_fastly_service_v1_httpslogging.go
  fastly/block_fastly_service_v1_logentries.go
  fastly/block_fastly_service_v1_logging_cloudfiles.go
  fastly/block_fastly_service_v1_logging_datadog.go
  fastly/block_fastly_service_v1_logging_digitalocean.go
  fastly/block_fastly_service_v1_logging_elasticsearch.go
  fastly/block_fastly_service_v1_logging_ftp.go
  fastly/block_fastly_service_v1_logging_googlepubsub.go
  fastly/block_fastly_service_v1_logging_heroku.go
  fastly/block_fastly_service_v1_logging_honeycomb.go
  fastly/block_fastly_service_v1_logging_kafka.go
  fastly/block_fastly_service_v1_logging_kinesis.go
  fastly/block_fastly_service_v1_logging_loggly.go
  fastly/block_fastly_service_v1_logging_logshuttle.go
  fastly/block_fastly_service_v1_logging_newrelic.go
  fastly/block_fastly_service_v1_logging_openstack.go
  fastly/block_fastly_service_v1_logging_scalyr.go
  fastly/block_fastly_service_v1_logging_sftp.go
  fastly/block_fastly_service_v1_package.go
  fastly/block_fastly_service_v1_papertrail.go
  fastly/block_fastly_service_v1_requestsetting.go
  fastly/block_fastly_service_v1_responseobject.go
  fastly/block_fastly_service_v1_s3logging.go
  fastly/block_fastly_service_v1_settings.go
  fastly/block_fastly_service_v1_snippet.go
  fastly/block_fastly_service_v1_splunk.go
  fastly/block_fastly_service_v1_sumologic.go
  fastly/block_fastly_service_v1_syslog.go
  fastly/block_fastly_service_v1_vcl.go
  fastly/block_fastly_service_v1_waf.go
  fastly/resource_fastly_service_v1.go
  fastly/service_attribute_definition.go
  fastly/service_crud_attribute_definition.go
Labels: enhancement

#469 Change to accept multi-pem blocks
  docs/resources/tls_certificate.md
  fastly/resource_fastly_tls_certificate.go
Labels: enhancement

#467 bump go-fastly version
  docs/resources/service_compute.md
  docs/resources/service_v1.md
  fastly/block_fastly_service_v1_dynamicsnippet.go
  fastly/block_fastly_service_v1_logging_newrelic.go
  fastly/block_fastly_service_v1_logging_newrelic_test.go
  fastly/block_fastly_service_v1_snippet.go
  fastly/resource_fastly_service_acl_entries_v1.go
  fastly/resource_fastly_service_acl_entries_v1_test.go
  fastly/resource_fastly_service_dynamic_snippet_content_v1.go
  fastly/resource_fastly_service_dynamic_snippet_content_v1_test.go
  fastly/resource_fastly_tls_subscription.go
  fastly/resource_fastly_tls_subscription_test.go
  go.mod
  go.sum
  vendor/github.com/fastly/go-fastly/v3/fastly/acl_entry.go
  vendor/github.com/fastly/go-fastly/v3/fastly/backend.go
  vendor/github.com/fastly/go-fastly/v3/fastly/client.go
  vendor/github.com/fastly/go-fastly/v3/fastly/errors.go
  vendor/github.com/fastly/go-fastly/v3/fastly/gzip.go
  vendor/github.com/fastly/go-fastly/v3/fastly/managed_logging.go
  vendor/github.com/fastly/go-fastly/v3/fastly/newrelic.go
  vendor/github.com/fastly/go-fastly/v3/fastly/purge.go
  vendor/github.com/fastly/go-fastly/v3/fastly/vcl_snippets.go
  vendor/modules.txt
Labels: bug, enhancement

#472 Clarify edge private dictionary usage
  docs/resources/service_compute.md
  docs/resources/service_v1.md
  fastly/block_fastly_service_v1_dictionary.go
Labels: documentation
