Repository fastly/terraform-provider-fastly, pull requests merged in 2022-01, with the labels that each got.

#519 Update VCL snippet type description
  docs/resources/service_v1.md
  fastly/block_fastly_service_v1_dynamicsnippet.go
  fastly/block_fastly_service_v1_snippet.go
  fastly/constants.go
Labels: documentation

#521 Add new `modsec_rule_ids` filter argument in `fastly_waf_rules` data resource
  docs/data-sources/waf_rules.md
  fastly/data_source_waf_rules.go
  fastly/data_source_waf_rules_test.go
  go.mod
  go.sum
  vendor/github.com/fastly/go-fastly/v5/fastly/acl_entry.go
  vendor/github.com/fastly/go-fastly/v5/fastly/client.go
  vendor/github.com/fastly/go-fastly/v5/fastly/dictionary_item.go
  vendor/github.com/fastly/go-fastly/v5/fastly/waf_rules.go
  vendor/github.com/peterhellberg/link/.travis.yml
  vendor/github.com/peterhellberg/link/LICENSE
  vendor/github.com/peterhellberg/link/README.md
  vendor/github.com/peterhellberg/link/doc.go
  vendor/github.com/peterhellberg/link/link.go
  vendor/modules.txt
Labels: enhancement

#527 Revamp `fastly_tls_subscription` examples
  docs/index.md
  docs/resources/tls_subscription.md
  examples/resources/tls_subscription_with_route53.tf
Labels: documentation

#528 Support updating TLS subscriptions in pending state #524
  fastly/resource_fastly_tls_subscription.go
  fastly/resource_fastly_tls_subscription_test.go
Labels: enhancement

#530 Add `activate` attribute support for `fastly_service_waf_configuration` resource
  docs/resources/service_waf_configuration.md
  fastly/block_fastly_waf_configuration_v1_active_rule_test.go
  fastly/block_fastly_waf_configuration_v1_exclusion_test.go
  fastly/resource_fastly_service_waf_configuration.go
  fastly/resource_fastly_service_waf_configuration_test.go
Labels: enhancement, feature request

#536 Support Terraform 1.x
  go.mod
  go.sum
  vendor/github.com/hashicorp/terraform-json/go.mod
  vendor/github.com/hashicorp/terraform-json/go.sum
  vendor/github.com/hashicorp/terraform-json/plan.go
  vendor/github.com/hashicorp/terraform-json/schemas.go
  vendor/github.com/hashicorp/terraform-json/state.go
  vendor/github.com/hashicorp/terraform-json/validate.go
  vendor/modules.txt
Labels: bug

#537 Add missing docs and attributes in versionless resources
  docs/index.md
  docs/resources/service_acl_entries.md
  docs/resources/service_dictionary_items.md
  docs/resources/service_dynamic_snippet_content.md
  examples/resources/service_acl_entries_ignore_changes.tf
  examples/resources/service_acl_entries_manage_entries.tf
  examples/resources/service_dictionary_items_manage_items.tf
  examples/resources/service_dynamic_snippet_content_ignore_changes.tf
  examples/resources/service_dynamic_snippet_content_manage_snippets.tf
  fastly/resource_fastly_service_dynamic_snippet_content.go
  fastly/resource_fastly_service_dynamic_snippet_content_test.go
  templates/resources/service_acl_entries.md.tmpl
  templates/resources/service_dictionary_items.md.tmpl
  templates/resources/service_dynamic_snippet_content.md.tmpl
Labels: enhancement, breaking-change, v1.0.0
